### ISSUE TITLE
UEFI

### ISSUE THREAD

**Issue by yxqsnz** [Sigmw/exherbo-instalacao#1]
por favor faça para UEFI.

**Comment by Sigmw** [comment]
Olá yxqsnz, bom dia! Posteriormente eu irei fazer pra UEFI sim, ainda preciso terminar de complementar algumas coisas na pós-Instalação, mas irei fazer!! Quando estiver pronto eu te mando mensagem.

**Comment by Pietro222222** [comment]
> Olá yxqsnz, bom dia! Posteriormente eu irei fazer pra UEFI sim, ainda preciso terminar de complementar algumas coisas na pós-Instalação, mas irei fazer!! Quando estiver pronto eu te mando mensagem.

isso é gay. faz um repo de pos instalação
